# <b>Numpy Basics</b>

## <center><img src = "https://us-east-1-02900067-view.menlosecurity.com/c/0/i/aHR0cHM6Ly91cGxvYWQud2lraW1lZGlhLm9yZy93aWtpcGVkaWEvY29tbW9ucy90aHVtYi8zLzMxL051bVB5X2xvZ29fMjAyMC5zdmcvNzY4cHgtTnVtUHlfbG9nb18yMDIwLnN2Zy5wbmc~"></center>

NumPy, which stands for Numerical Python, is a library consisting of multidimensional array objects and a collect of routines for processing those arrays. Using NumPy, mathematical and logical operation on arrays can be performed.

Installation syntax:

    pip install numpy
  
- Main object: `ndarry`

## <b>ndarray</b>

The most important object defined in NumPy is an N-dimensional array type called ndarray. It describes the collection of items of the same type. Items in the collection can be accessed using a zero-based index.

Every item in an ndarray takes the same size of block in the memory. Each element in ndarray is an object of data-type object (called dtype) Any item  extracted from dnarry object(by slicing) is repersented by a Python object of one of the array scalar types.

You import the function in python by calling `import numpy`. The basic ndarray is created using an array function in NumPy as follows

In [1]:
import numpy
numpy.array

<function numpy.array>

## <b>How do I create Arrays in Python</b>

- Create an array from a regular Python list or tuple using array function
- The type of the resulting array is deduced from the type of the elements in the sequences

It creates an ndarray from any object exposing array interface, or from any method that returns an array.

In [2]:
import numpy as np

# From list: 1D array
my_list = [10, 20, 30]
np.array(my_list)

array([10, 20, 30])

In [3]:
# From list: 2D array

new_lists = [[2, 4, 6], [8, 10, 12], [14, 16, 18]]
np.array(new_lists)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [4]:
type(np.array(new_lists))

numpy.ndarray

In [5]:
# From list: 3D array
three_dimensional_list = [[1, 2, 3], [4, 5, 6],], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]
np.array(three_dimensional_list)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

`ndarray` is also known by the alias `array`. Note that `numpy.array` is not the same as the Standard Python Library class `array.array`, which only handles one-dimensional arrays and offers less functionality. The more important attributes of an `ndarray` object are:

- <b><i>ndarray.shape</i></b> the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with <i>n</i> rows and <i>m</i> columns, `shape` will be `(n, m)`. The length of the `shape` tuple is therefore the rank, or number of dimensions, `ndim`

- <b><i>ndarray.dtype</i></b> an object describing the type of the elements in the array. One can create or specify dtype's using standard Python types. Additionally NumPy provides types of its own: `numpy.int32`, `numpy.int16` and `numpy.float64` are some examples.

- <b><i>ndarray.reshape</i></b> Returns an array containing the same data with a new shape.

## <b>numpy.dtype</b>

The data type of dtype describes that kind of elements that are contained within the array.

- <b>bool</b>: Boolean values
- <b>int</b>: Integer values. Can be int16, int32, or int64
- <b>float</b>: Floating point values. Can be float16, float32, or float64

- <b>string</b>: Text can be a string or unicode(this distinction is greatly simplified in Python 3)

In [13]:
my_list = [10, 20, 30]

arr = np.array(my_list)

print(type(arr))
print(type(arr.dtype))
print(type(arr.shape))
print(arr.dtype)
print(arr.shape)

<class 'numpy.ndarray'>
<class 'numpy.dtype[int64]'>
<class 'tuple'>
int64
(3,)


# <b>NumPy Built-in methods</b>

`arange`

`arange([start], [step], [dtype])`: Returns an array with evenly spaced elements as per interval. The interval mentioned is half opened i.e <b>[Start], [Stop]</b> (similar to Python `range()` function)

## <b>`zeros` and `ones`</b>

Generate arrays of all zeros and ones

In [15]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones((2, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## <b>`linspace`</b>

Linespace: Return <b>evenly spaced</b> numbers over a specified interval.

    linspace(start, stop, num=50, endpoint=True, retstep=False)

- Will return `num` number of values
- Equally spaced samples in the closed interval [start, stop] or the half-open interval [start, stop]
- Closed or half-open interval depends on whether 'endpoint' is True or False

In [18]:
# Divide into 7 interval from 0 to 10
np.linspace(0, 10, 7)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

## <b>How to generate Random Numbers</b>

Numpy also has lots of ways to create random number arrays of given space
- <b>`read`</b>:

`numpy.random.rand(d0, d1, _, dn)` Creates an array of the given shape and populates it with random samples from a <b>uniform distribution</b>
- <b>`randn`</b>:

`numpy.random.randn(d0, d1, _, dn)` creates an array of specified shape and fills it with random values as per <b>standard normal distribution</b>

If posistive arguments are provided, randn generates an array of shape(d0, d1, ....., dn), filled with random floats sampled from a univariate "normal"(Gaussian) distribution of mean 0 and variance 1 (if any of the d_i are floats, they are first converted to integers by trincation).

A single float randomly sampled from the distribution is returned if no argument is provided.
- `<b>randint</b>`:

Return random integers from the "discrete uniform" distribution of the specified dtype in the "half-open" interval [low, high]. If high is None (the default), then results are from [0, low].

In [21]:
# Random number (uniform distribution) array of shape (3, 4)

np.random.rand(3, 4)

array([[0.38853259, 0.27589311, 0.78888341, 0.27100624],
       [0.44844966, 0.37804905, 0.71825243, 0.18526264],
       [0.05648509, 0.46936773, 0.31125796, 0.85707245]])

In [22]:
# Random number (standard normal distribution) array of shape (2, 3)

print(np.random.rand(3, 4))

[[0.81565486 0.68357632 0.84635791 0.08291174]
 [0.56958565 0.7384221  0.8506535  0.54130385]
 [0.57811922 0.1989181  0.03385945 0.47937136]]


In [24]:
# 10 random integers up to 50 (exclusive). This makes the start value default to 0.
# The size parameter dictates the return array shape

np.random.randint(50, size=(4,4))

array([[ 6, 11, 28,  1],
       [17,  0, 34, 39],
       [ 4, 26,  6, 19],
       [ 5,  4, 41, 23]])